"""add project status, context, chat

Revision ID: d020083e2ec6
Revises: 947f498412d3
Create Date: 2026-02-19 16:38:24.160900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd020083e2ec6'
down_revision: Union[str, Sequence[str], None] = '947f498412d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatmessage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatmessage_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmessage_session_id'), ['session_id'], unique=False)

    op.create_table('projectcontext',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_agent_id', sa.Uuid(), nullable=True),
    sa.Column('source_step_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['source_step_id'], ['step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projectcontext', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projectcontext_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_projectcontext_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_projectcontext_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DECOMMISSIONED', name='projectstatus'), nullable=False, server_default='ACTIVE'))
        batch_op.create_index(batch_op.f('ix_project_status'), ['status'], unique=False)

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.alter_column('mc_task_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('mc_board_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.alter_column('mc_board_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('mc_task_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_status'))
        batch_op.drop_column('status')

    with op.batch_alter_table('projectcontext', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projectcontext_project_id'))
        batch_op.drop_index(batch_op.f('ix_projectcontext_key'))
        batch_op.drop_index(batch_op.f('ix_projectcontext_category'))

    op.drop_table('projectcontext')
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatmessage_session_id'))
        batch_op.drop_index(batch_op.f('ix_chatmessage_project_id'))

    op.drop_table('chatmessage')
    # ### end Alembic commands ###
